### PR TITLE
Disable broken UniDict recipe for some plates. 

### PR DESCRIPTION
**Pull request by CrossVas**
image

### CODE REVIEW

**Comment by CrossVas** [comment]
Also I noticed that there is no other way to craft steel plates beside TE's Compactor

**Comment by Trinsdar** [comment]
this thing again :angry:
also that won't work, cause it will actually remove the recipe, which I don't want. I already have a script to fix this in another project of mine I'll just copy. thanks for doing this though, it still helped me to figure out which ones I need to do.

**Comment by Trinsdar** [comment]
also not sure what you mean, I can craft them with the plate bending machine and fluid caster too

**Comment by CrossVas** [comment]
I meant early game but... NVM and blame UniDict for that.

**Pull request closed without merging**
